server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mio_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1314Sakura
  mvc:
  pathmatch:
  matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  main:
    allow-circular-references: true
  ##¥Ú”°mybatis SQL
    #logging.level.com.sakura.mio_order.mapper= debug
logging:
  level:
    com.mio.mall.mbg.mapper : debug